openapi: 3.0.0
info:
  title: Hie API
  description: API document of Hie
  version: 0.1.0
servers:
  - url: http://localhost:3140
    description: Local server
tags:
  - name: Tags
  - name: Tags relation
  - name: Items
  - name: Items relation
  - name: Folders
  - name: Image
paths:
  /api/tags:
    $ref: "./tags.yaml"
  /api/tags/{id}:
    $ref: "./tags_id.yaml"
  /api/tags/relation:
    $ref: "./tags_relation.yaml"

  /api/items:
    $ref: "./items.yaml"
  /api/items{id}:
    $ref: "./items_id.yaml"
  /api/items/relation:
    $ref: "./items_relation.yaml"

  /api/folders:
    $ref: "./folders.yaml"
  /api/folders/{id}:
    $ref: "./folders_id.yaml"

  /api/image/{path}:
    $ref: "./image_path.yaml"
