openapi: 3.0.0
info:
  title: Hie API
  description: API document of Hie
  version: 0.1.0
servers:
  - url: /
    description: Local server
  - url: http://localhost:3000
    description: Local develop server
tags:
  - name: Tags
  - name: Tags relation
  - name: Items
  - name: Items relation
  - name: Folders
  - name: Image
paths:
  /api/tags:
    $ref: "./tags/index.yaml"
  /api/tags/{id}:
    $ref: "./tags/id.yaml"
  /api/tags/relation:
    $ref: "./tags/relation.yaml"

  /api/items:
    $ref: "./items/index.yaml"
  /api/items{id}:
    $ref: "./items/id.yaml"
  /api/items/relation:
    $ref: "./items/relation.yaml"

  /api/folders:
    $ref: "./folders/index.yaml"
  /api/folders/{id}:
    $ref: "./folders/id.yaml"

  /api/image/{path}:
    $ref: "./image/path.yaml"
