openapi: 3.0.0
info:
  title: Hie API
  description: API document of Hie
  version: 0.1.0
servers:
  - url: http://localhost:3140
    description: Local server
tags:
  - name: Tags
    description: Operations related to tags
  - name: Tags relation
    description: Operations related to tag relation
  - name: Items
    description: Operations related to items
  - name: Items relation
    description: Operations related to item relation
  - name: Folders
    description: Operations related to folders
paths:
  /api/tags:
    $ref: "./tags.yaml"
  /api/tags/{tagId}:
    $ref: "./tags_id.yaml"

  /api/items:
    $ref: "./items.yaml"
  /api/tags/relation:
    $ref: "./tags_relation.yaml"
  /api/items/relation:
    $ref: "./items_relation.yaml"
  /api/folders:
    $ref: "./folders.yaml"
